# Generated by Django 4.1.6 on 2023-02-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('jobId', models.AutoField(primary_key=True, serialize=False)),
                ('jobName', models.CharField(max_length=122)),
                ('jobDescription', models.CharField(max_length=122)),
            ],
        ),
    ]
