# Generated by Django 4.1.6 on 2023-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobpost', '0002_alter_jobpost_jobdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Addnotification', models.CharField(max_length=1000)),
            ],
        ),
    ]
